exports.BattleLocationdex = {
    pallettown: {
        name: "Pallet Town",
        landslot1: "shedinja",
        landslot2: "shedinja",
        landslot3: "shedinja",
        landslot4: "shedinja",
        landslot5: "shedinja",
        landslot6: "shedinja",
        landslot7: "shedinja",
        landslot8: "shedinja",
        landslot9: "shedinja",
        landslot10: "shedinja",
        fishslot1: "shedinja",
        fishslot2: "shedinja",
        fishslot3: "shedinja",
        fishslot4: "shedinja",
        fishslot5: "shedinja",
        fishslot6: "shedinja",
        fishslot7: "shedinja",
        fishslot8: "shedinja",
        fishslot9: "shedinja",
        fishslot10: "shedinja",
        waterslot1: "shedinja",
        waterslot2: "shedinja",
        waterslot3: "shedinja",
        waterslot4: "shedinja",
        waterslot5: "shedinja",
        waterslot6: "shedinja",
        waterslot7: "shedinja",
    },
    route1:{
        name: "Route 1",
        landslot1: "aipom",
        landslot2: "deerling",
        landslot3: "rookidee",
        landslot4: "rookidee",
        landslot5: "skwovet",
        landslot6: "yungoos",
        landslot7: "pidgey",
        landslot8: "pidgey",
        landslot9: "drifloon",
        landslot10: "drifloon",
    },
    viridiancity: {
        name: "Viridian City",
        landslot1: "shedinja",
        landslot2: "shedinja",
        landslot3: "shedinja",
        landslot4: "shedinja",
        landslot5: "shedinja",
        landslot6: "shedinja",
        landslot7: "shedinja",
        landslot8: "shedinja",
        landslot9: "shedinja",
        landslot10: "shedinja",
        fishslot1: "poliwag",
        fishslot2: "tympole",
        fishslot3: "tympole",
        fishslot4: "wooperpaldea",
        fishslot5: "wooperpaldea",
        fishslot6: "binacle",
        fishslot7: "binacle",
        fishslot8: "lotad",
        fishslot9: "lotad",
        fishslot10: "lotad",
    },
    route22: {
        name: "Route 22",
        landslot1: "shedinja",
        landslot2: "shedinja",
        landslot3: "shedinja",
        landslot4: "shedinja",
        landslot5: "shedinja",
        landslot6: "shedinja",
        landslot7: "shedinja",
        landslot8: "shedinja",
        landslot9: "shedinja",
        landslot10: "shedinja", 
    },
    route2: {
        name: "Route 2",
        landslot1: "numel",
        landslot2: "vulpix",
        landslot3: "larvesta",
        landslot4: "fletchling",
        landslot5: "magby",
        landslot6: "rolycoly",
        landslot7: "houndour",
        landslot8: "rolycoly",
        landslot9: "houndour",
        landslot10: "houndour",
    },
    viridianforest: {
        name: "Viridian Forest",
        landslot1: "sewaddle",
        landslot2: "venonat",
        landslot3: "weedle",
        landslot4: "morelull",
        landslot5: "cutiefly",
        landslot6: "nymble",
        landslot7: "kricketot",
        landslot8: "kricketot",
        landslot9: "shroomish",
        landslot10: "shroomish"
    },
    diglettcave: {
        name: "Diglett Cave",
        landslot1: "shedinja",
        landslot2: "shedinja",
        landslot3: "shedinja",
        landslot4: "shedinja",
        landslot5: "shedinja",
        landslot6: "shedinja",
        landslot7: "shedinja",
        landslot8: "shedinja",
        landslot9: "shedinja",
        landslot10: "shedinja", 
    },
    vermillioncity: {
        name: "Vermillion City",
        landslot1: "shedinja",
        landslot2: "shedinja",
        landslot3: "shedinja",
        landslot4: "shedinja",
        landslot5: "shedinja",
        landslot6: "shedinja",
        landslot7: "shedinja",
        landslot8: "shedinja",
        landslot9: "shedinja",
        landslot10: "shedinja", 
    },
    route11: {
        name: "Route 11",
        landslot1: "pidgey",
        landslot2: "fletchling",
        landslot3: "pikipek",
        landslot4: "pikipek",
        landslot5: "hoppip",
        landslot6: "farfetchdgalar",
        landslot7: "gligar",
        landslot8: "squawkabilly",
        landslot9: "togepi",
        landslot10: "togepi", 
    },
};
